version: '3.7'
services:

  db-spring:
    image: mysql:8.0
    container_name: 'mysql-spring'
    ports:
      - 3304:3306
    volumes:
      - /mysql-spring/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234