// Cadastrar Usuário;
POST http://localhost:8080/usuario/register
Content-Type: application/json

{
    "name": "Daniel_Test",
    "email": "daniel@program.com",
    "password": "daniel1234"
}

// Fazer Login;
POST http://localhost:8080/usuario/login
Content-Type: application/json

{
    "name": "Daniel_Test",
    "email": "daniel@program.com",
    "password": "daniel1234"
}

// 